// This file is auto-generated by Convex
// It re-exports server utilities with proper typing
import {
  mutationGeneric as mutation,
  queryGeneric as query,
  actionGeneric as action,
  internalMutationGeneric as internalMutation,
  internalQueryGeneric as internalQuery,
  internalActionGeneric as internalAction,
  defineTable,
  defineSchema,
} from "convex/server";

export { mutation, query, action, internalMutation, internalQuery, internalAction, defineTable, defineSchema };
